<h1>Unsupervised Learning Chapter 4 : Principal Component Analysis (PCA) </h1>

<h2>Refrance:</h2>
https://medium.com/@raghavan99o/principal-component-analysis-pca-explained-and-implemented-eeab7cb73b72

https://medium.com/100-days-of-algorithms/day-92-pca-bdb66840a8fb

https://medium.com/journey-2-artificial-intelligence/unraveling-pca-principal-component-analysis-in-python-d23b081409cf


<b>Book</b><br>
machin learning.pdf

PCA is a statistical technique which reduces the dimensions  n(> 10) of the data and help us understand,<br>
Principal components are basically vectors that are linearly uncorrelated and have a variance with in data.<br>
From the principal components top p is picked which have the most variance.<br>
Our goal separate data by drawing a line (or a plane) between data. If we find out the dimension which has maximum variance, then it solves part of the problem, now all we have to use suitable algorithm to draw the line or plane which splits the data.


<h2>Theory:</h2>

The goal of PCA is to perform a linear. projection of the data onto a lower-dimensional subspace where the variance is maximized.

Let’s say we have a bunch of multi-dimensional data stored in a matrix X. Each row represents a sample, and each column represents a variable.<br>

We say that two variables are correlated if there is a linear relationship in between them.<br>Their scatterplot may look similarly to this one:

<img src="https://cdn-images-1.medium.com/max/1600/1*VUuO9kIhXOyhLD6gE6dyGQ.png"></img>
https://cdn-images-1.medium.com/max/1600/1*VUuO9kIhXOyhLD6gE6dyGQ.png

On the other hand, the variables on the next scatterplot are uncorrelated.<br>

While the first plot seems to be more useful, PCA takes the advantage of the second one.

<h3>implement PCA</h3>

Lets begin by generating random data with 3 dimensions with 40 samples . We will have two class with 20 samples per class.

In [1]:
import numpy as np
np.random.seed(1)

vec1 = np.array([0, 0, 0])
mat1 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
sample_for_class1 = np.random.multivariate_normal(vec1, mat1, 20).T
assert sample_for_class1.shape == (3, 20), "The dimension of the sample_for_class1 matrix is not 3x20"

vec2 = np.array([1, 1, 1])
mat2 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
sample_for_class2 = np.random.multivariate_normal(vec2, mat2, 20).T
assert sample_for_class2.shape == (3, 20), "The dimension of the sample_for_class2 matrix is not 3x20"

all_data = np.concatenate((sample_for_class1, sample_for_class2), axis=1)
assert all_data.shape == (3, 40), "The dimension of the all_data matrix is not 3x20"

In [2]:
mean_dim1 = np.mean(all_data[0, :])
mean_dim2 = np.mean(all_data[1, :])
mean_dim3 = np.mean(all_data[2, :])

mean_vector = np.array([[mean_dim1], [mean_dim2], [mean_dim3]])

print('The Mean Vector:\n', mean_vector)

scatter_matrix = np.zeros((3,3))
for i in range(all_data.shape[1]):
    scatter_matrix += (all_data[:, i].reshape(3, 1) - mean_vector).dot((all_data[:, i].reshape(3, 1) - mean_vector).T)
print('The Scatter Matrix is :\n', scatter_matrix)

The Mean Vector:
 [[0.41667492]
 [0.69848315]
 [0.49242335]]
The Scatter Matrix is :
 [[38.4878051  10.50787213 11.13746016]
 [10.50787213 36.23651274 11.96598642]
 [11.13746016 11.96598642 49.73596619]]


Now we know how each of variables are related to each other. 

Now we use the numpy library to compute the Eigenvectors and eigenvalues:

In [3]:
eig_val, eig_vec = np.linalg.eig(scatter_matrix)

By default numpy or any stats library gives out eigenvectors of unit length. Lets verify it

In [4]:
for ev in eig_vec:
    np.testing.assert_array_almost_equal(1.0, np.linalg.norm(ev))

In [6]:
eig_val_sc, eig_vec_sc =eig_val, eig_vec

In [7]:
# We Make a list of tuple containing (eigenvalue, eigenvector)
eig_pairs = [(np.abs(eig_val_sc[i]), eig_vec_sc[:,i]) for i in range(len(eig_val_sc))]

# We then Sort list of tuples by the eigenvalue
eig_pairs.sort(key=lambda x: x[0], reverse=True)

# verify that the list is correctly sorted by decreasing eigenvalues
for i in eig_pairs:
    print(i[0])

65.16936779078195
32.69471296321799
26.596203282097097


Now we choose k the largest eigenvectors :

In [8]:
matrix_w = np.hstack((eig_pairs[0][1].reshape(3,1), eig_pairs[1][1].reshape(3,1)))
print('Matrix W:\n', matrix_w)

Matrix W:
 [[-0.49210223 -0.64670286]
 [-0.47927902 -0.35756937]
 [-0.72672348  0.67373552]]


In [9]:
transformed = matrix_w.T.dot(all_samples)
assert transformed.shape == (2,40), "The matrix is not 2x40 dimensional."

NameError: name 'all_samples' is not defined

<img src="https://cdn-images-1.medium.com/max/1600/1*QMqMeGy6sp-FSlZ0RSQWpg.png"></img>
https://cdn-images-1.medium.com/max/1600/1*QMqMeGy6sp-FSlZ0RSQWpg.png